apiVersion: v1
kind: ServiceAccount
metadata:
  name: externalsecret-sa
  namespace: app
  labels:
  annotations:
    eks.amazonaws.com/role-arn: {{ROLE_ARN}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-generic-sa
  namespace: app
  labels:
  annotations:
    eks.amazonaws.com/role-arn: {{ROLE_ARN_AWS_GENERIC}}
