apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: dm-secretstore
  namespace: app
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: externalsecret-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dm-externalsecret
  namespace: app
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: dm-secretstore
    kind: SecretStore
  target:
    name: dm-externalsecret
    creationPolicy: Owner
  data:
    - secretKey: UI_APPCONFIG
      remoteRef:
        key: /dm/{{ENV_NAME}}/appsettings/ui
    - secretKey: API_APPCONFIG
      remoteRef:
        key: /dm/{{ENV_NAME}}/appsettings/api
    - secretKey: USERS_APPCONFIG
      remoteRef:
        key: /dm/{{ENV_NAME}}/appsettings/users
