apiVersion: apps/v1
kind: Deployment
metadata:
  name: dm-fast-catalogue
  namespace: app
  labels:
    app: dm-fast-catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dm-fast-catalogue
  template:
    metadata:
      labels:
        app: dm-fast-catalogue
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
      - name: c-dm-fast-catalogue
        image: {{IMG}}
        resources:
          requests:
            memory: "1Gi"
            cpu: "512m"
        envFrom:
          - secretRef:
              name: dm-catalogue-envs
        ports:
        - name: http
          containerPort: 3000
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux

