apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dm-externalsecret
  namespace: frontend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: eso-created-secret
    creationPolicy: Owner
  data:
    - secretKey: API_ENDPOINT
      remoteRef:
        key: /dm/dev/data-marketplace/gen/API_ENDPOINT
    - secretKey: SSO_AUTH_URL
      remoteRef:
        key: /dm/dev/data-marketplace/gen/SSO_AUTH_URL
    - secretKey: SSO_CALLBACK_URL
      remoteRef:
        key: /dm/dev/data-marketplace/gen/SSO_CALLBACK_URL
    - secretKey: SSO_CLIENT_ID
      remoteRef:
        key: /dm/dev/data-marketplace/gen/SSO_CLIENT_ID
    - secretKey: SSO_CLIENT_SECRET
      remoteRef:
        key: /dm/dev/data-marketplace/gen/SSO_CLIENT_SECRET
    - secretKey: JWT_AUD
      remoteRef:
        key: /dm/dev/data-marketplace/gen/JWT_AUD
    - secretKey: JWKS_URL
      remoteRef:
        key: /dm/dev/data-marketplace/gen/JWKS_URL
            