apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must be in the form: <plural>.<group>
  name: dm-secretstores.external-secrets.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: external-secrets.io
  scope: Namespaced
  names:
    # kind is normally the CamelCased singular type. 
    kind: ClusterSecretStore
    # singular name to be used as an alias on the CLI
    singular: dm-secretstore
    # plural name in the URL: /apis/<group>/<version>/<plural>
    plural: dm-secretstores
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            x-kubernetes-preserve-unknown-fields: true