apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: dm-secretstore
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-north-1
      auth:
        jwt:
          serviceAccountRef:
            name: dm-frontend-sa