apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: dm-secretstore
  namespace: app
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: externalsecret-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dm-externalsecret
  namespace: app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: dm-secretstore
    kind: SecretStore
  target:
    name: dm-externalsecret
    creationPolicy: Owner
  data:
    - secretKey: API_ENDPOINT
      remoteRef:
        key: /dm/dev/services/API_ENDPOINT
    - secretKey: SSO_AUTH_URL
      remoteRef:
        key: /dm/dev/services/SSO_AUTH_URL
    - secretKey: SSO_CALLBACK_URL
      remoteRef:
        key: /dm/dev/services/SSO_CALLBACK_URL
    - secretKey: SSO_CLIENT_ID
      remoteRef:
        key: /dm/dev/services/SSO_CLIENT_ID
    - secretKey: SSO_CLIENT_SECRET
      remoteRef:
        key: /dm/dev/services/SSO_CLIENT_SECRET
    - secretKey: JWT_AUD
      remoteRef:
        key: /dm/dev/services/JWT_AUD
    - secretKey: JWKS_URL
      remoteRef:
        key: /dm/dev/services/JWKS_URL
    - secretKey: OPS_API_KEY
      remoteRef:
        key: /dm/dev/services/OPS_API_KEY
