apiVersion: apps/v1
kind: Deployment
metadata:
  name: dm-backend-api
  namespace: app
  labels:
    app: dm-backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dm-backend-api
  template:
    metadata:
      labels:
        app: dm-backend-api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
      - name: c-dm-backend-api
        image: {{IMG}}
        resources:
          requests:
            memory: "0.5Gi"
            cpu: "0.25"
        env:
          - name: TRIPLESTORE_URL
            value: http://dm-backend-api-fuseki-service
          - name: DATASET_NAME
            value: ds
          - name: JWT_AUD
            valueFrom:
              secretKeyRef:
                name: dm-externalsecret
                key: JWT_AUD
                optional: false
          - name: JWKS_URL
            valueFrom:
              secretKeyRef:
                name: dm-externalsecret
                key: JWKS_URL
                optional: false
          - name: OPS_API_KEY
            valueFrom:
              secretKeyRef:
                name: dm-externalsecret
                key: OPS_API_KEY
                optional: false
        ports:
        - name: http
          containerPort: 8000
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux
