apiVersion: apps/v1
kind: Deployment
metadata:
  name: dm-frontend
  namespace: app
  labels:
    app: dm-frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dm-frontend-app
  template:
    metadata:
      labels:
        app: dm-frontend-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
      - name: c-dm-frontend
        image: {{IMG}}
        resources:
          requests:
            memory: "0.5Gi"
            cpu: "0.25"
        env:
          - name: API_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: dm-externalsecret
                key: API_ENDPOINT
                optional: false
          - name: SSO_AUTH_URL
            valueFrom:
              secretKeyRef:
                name: dm-externalsecret
                key: SSO_AUTH_URL
                optional: false
          - name: SSO_CALLBACK_URL
            valueFrom:
              secretKeyRef:
                name: dm-externalsecret
                key: SSO_CALLBACK_URL
                optional: false
          - name: SSO_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: dm-externalsecret
                key: SSO_CLIENT_ID
                optional: false
          - name: SSO_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: dm-externalsecret
                key: SSO_CLIENT_SECRET
                optional: false
        ports:
        - name: http
          containerPort: 3000
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux

