apiVersion: apps/v1
kind: Deployment
metadata:
  name: dm-backend-api-fuseki
  namespace: app
  labels:
    app: dm-backend-api-fuseki
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: dm-backend-api-fuseki
  template:
    metadata:
      labels:
        app: dm-backend-api-fuseki
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64

      initContainers:
      - name: fs-owner-change
        image: busybox
        command:
        - chown
        - "9008:root"
        - "/fuseki-base/databases"
        volumeMounts:
        - mountPath: /fuseki-base/databases
          name: persistent-storage



      containers:
      - name: c-dm-backend-api-fuseki
        image: {{IMG}}
        volumeMounts:
          - name: persistent-storage
            mountPath: /fuseki-base/databases 
        resources:
          requests:
            memory: "0.5Gi"
            cpu: "0.25"
        env:
          - name: ENABLE_UPDATE
            value: "true"
          - name: ENABLE_DATA_WRITE
            value: "true"
          - name: ENABLE_UPLOAD
            value: "true"
        ports:
        - name: http
          containerPort: 3030
        imagePullPolicy: IfNotPresent
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: efs-claim
      nodeSelector:
        kubernetes.io/os: linux
