name: environment-configuration-update

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'Dev'
        type: choice
        options:
          - Dev
        # - Test
        # - Prod
        # - Custom
      TerraformAction:
        type: choice
        description: 'Terraform With Approvals'
        required: true
        default: 'init + plan'
        options:
          - 'init+plan'
          - 'init+plan+apply'
          - 'approval+destroy'

permissions:
  id-token: write
  contents: read

jobs:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#~~ 01 TerraformInitPlanOnly
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  TerraformInitPlanOnly:
    name: TerraformInitPlanOnly
    runs-on: ubuntu-latest
    if: inputs.TerraformAction == 'init+plan'

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4.2.2

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          role-session-name: github-actions
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: TerraformInitiate EC2
        id: TerraformInitiateEC2
        uses: forgedconcepts/aws-ssm-send-command-action@v1.1.1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          targets: |
            [${{ secrets.INSTANCE_ID }}]
          document-name: AWS-RunShellScript
          parameters: |
            {"commands":[
              "su - ssm-user -c \"/home/ssm-user/bin/tfrunner.sh ${{ inputs.environment }} ${{ inputs.TerraformAction }} ${{ github.job }} \""
            ]}

      - name: Get and Show PLANOUTFILE
        run: |
          aws s3 cp s3://jpbackupbucket20250502/PLANOUTFILE.txt ./PLANOUTFILE.txt
          echo "#~~ INFO: PLANOUTFILE CONTENT START ~~~~~~~"
          cat ./PLANOUTFILE.txt
          echo "#~~ INFO: PLANOUTFILE CONTENT END ~~~~~~~~~"

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#~~ 02 TerraformInitPlan
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  TerraformInitPlan:
    name: TerraformInitPlan
    runs-on: ubuntu-latest
    if: inputs.TerraformAction == 'init+plan+apply'

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4.2.2

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          role-session-name: github-actions
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: TerraformInitiate EC2
        id: TerraformInitiateEC2
        uses: forgedconcepts/aws-ssm-send-command-action@v1.1.1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          targets: |
            [${{ secrets.INSTANCE_ID }}]
          document-name: AWS-RunShellScript
          parameters: |
            {"commands":[
              "su - ssm-user -c \"/home/ssm-user/bin/tfrunner.sh ${{ inputs.environment }} ${{ inputs.TerraformAction }} ${{ github.job }} \""
            ]}

      - name: Get and Show PLANOUTFILE
        run: |
          aws s3 cp s3://jpbackupbucket20250502/PLANOUTFILE.txt ./PLANOUTFILE.txt
          echo "#~~ INFO: PLANOUTFILE CONTENT START ~~~~~~~"
          cat ./PLANOUTFILE.txt
          echo "#~~ INFO: PLANOUTFILE CONTENT END ~~~~~~~~~"

#~~~~~~~~~~~~~~~~~~~~~~~
#~~ 02b Manual Approval For Apply
#~~~~~~~~~~~~~~~~~~~~~~~

  manual-approval-for-apply:
    name: Manual Approval For Apply
    runs-on: ubuntu-latest
    needs: ["TerraformInitPlan"]
    if: success() && inputs.TerraformAction == 'init+plan+apply'

    permissions:
      issues: write

    steps:
      - name: Await Manual Approval
        uses: trstringer/manual-approval@v1.10.0
        with:
          secret: ${{ github.TOKEN }}
          approvers: soydaner,JohnPalmerGDS,denis-davidov-gds
          minimum-approvals: 1
          issue-title: "Manual Approval Required for Terraform APPLY"
          issue-body: "Please approve or deny the deployment."

  TerraformApply:
    name: TerraformApply
    runs-on: ubuntu-latest
    needs: ["manual-approval-for-apply"]
    if: inputs.TerraformAction == 'init+plan+apply'
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4.2.2

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          role-session-name: github-actions2
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: TerraformApply EC2
        uses: forgedconcepts/aws-ssm-send-command-action@v1.1.1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          targets: |
            [${{ secrets.INSTANCE_ID }}]
          document-name: AWS-RunShellScript
          parameters: |
            {"commands":[
              "echo 'ENV: ${{ inputs.environment }} TFACTION: ${{ inputs.TerraformAction }} GHJOB: ${{ github.job }}'",
              "su - ssm-user -c \"/home/ssm-user/bin/tfrunner.sh ${{ inputs.environment }} ${{ inputs.TerraformAction }} ${{ github.job }} \""
            ]}

      - name: Get and Show APPLYLOG
        run: |
          aws s3 cp s3://jpbackupbucket20250502/APPLYLOG.txt ./APPLYLOG.txt
          echo "#~~ INFO: APPLYLOG CONTENT START ~~~~~~~"
          cat ./APPLYLOG.txt
          echo "#~~ INFO: APPLYLOG CONTENT END ~~~~~~~~~"

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#~~ 03 Manual Approval + Destroy
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  manual-approval-for-destroy:
    name: Manual Approval For Destroy
    runs-on: ubuntu-latest
    if: inputs.TerraformAction == 'approval+destroy'
#   needs: ["TerraformInitPlan"]
#   if: success()

    permissions:
      issues: write

    steps:
      - name: Await Manual Approval
        uses: trstringer/manual-approval@v1.10.0
        with:
          secret: ${{ github.TOKEN }}
          approvers: soydaner,JohnPalmerGDS,denis-davidov-gds
          minimum-approvals: 1
          issue-title: "Manual Approval Required for Terraform DESTROY"
          issue-body: "Please approve or deny the destroy."


  TerraformDestroy:
    name: TerraformDestroy
    runs-on: ubuntu-latest
    if: inputs.TerraformAction == 'approval+destroy'
    needs: ["manual-approval-for-destroy"]
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4.2.2

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          role-session-name: github-actions2
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: TerraformApply EC2
        uses: forgedconcepts/aws-ssm-send-command-action@v1.1.1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          targets: |
            [${{ secrets.INSTANCE_ID }}]
          document-name: AWS-RunShellScript
          parameters: |
            {"commands":[
              "echo 'ENV: ${{ inputs.environment }} TFACTION: ${{ inputs.TerraformAction }} GHJOB: ${{ github.job }}'",
              "su - ssm-user -c \"/home/ssm-user/bin/tfrunner.sh ${{ inputs.environment }} ${{ inputs.TerraformAction }} ${{ github.job }} \""
            ]}

      - name: Get and Show DESTROYLOG
        run: |
          aws s3 cp s3://jpbackupbucket20250502/DESTROYLOG.txt ./DESTROYLOG.txt
          echo "#~~ INFO: DESTROYLOG CONTENT START ~~~~~~~"
          cat ./DESTROYLOG.txt
          echo "#~~ INFO: DESTROYLOG CONTENT END ~~~~~~~~~"
